const THUMBS = ["tg1", "tg2", "tg3", "tg4", "tg5", "tg6"];

export const ENTITIES = {
  banner: {
    table: "gyaan_banner",
    label: "Home Banner",
    order: "sort",
    columns: ["title", "eyebrow", "cta_label", "active"],
    fields: [
      { name: "title", label: "Banner heading", type: "text", required: true },
      { name: "eyebrow", label: "Small label (top)", type: "text", hint: "e.g. 🕉 Now Streaming" },
      { name: "subtitle", label: "Sub text", type: "textarea" },
      { name: "image_url", label: "Background image URL", type: "text", hint: "Optional — leave blank for the default gradient" },
      { name: "cta_label", label: "Button text", type: "text", hint: "e.g. Watch Live Now" },
      { name: "cta_link", label: "Button link", type: "text", hint: "e.g. /live or https://…" },
      { name: "active", label: "Show on home", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  kathakaar: {
    table: "gyaan_kathakaar",
    label: "Kathakaar",
    order: "sort",
    columns: ["name", "role", "place", "featured"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "initials", label: "Initials (avatar)", type: "text", hint: "e.g. MB" },
      { name: "role", label: "Role", type: "text", hint: "e.g. Ram Katha" },
      { name: "languages", label: "Languages", type: "text" },
      { name: "ashram", label: "Ashram", type: "text" },
      { name: "place", label: "Place", type: "text" },
      { name: "image_url", label: "Image URL", type: "text" },
      { name: "videos_url", label: "Videos URL", type: "text" },
      { name: "contact_phone", label: "Contact phone", type: "text" },
      { name: "contact_email", label: "Contact email", type: "text" },
      { name: "featured", label: "Featured on home", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  live: {
    table: "gyaan_live",
    label: "Live",
    order: "sort",
    columns: ["title", "kind", "place", "is_live"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "kind", label: "Type", type: "select", options: ["darshan", "katha"] },
      { name: "place", label: "Place / By", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "stream_url", label: "Stream URL", type: "text" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "viewers", label: "Viewers label", type: "text", hint: "e.g. 12.4k" },
      { name: "is_live", label: "Live now", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  programmes: {
    table: "gyaan_programmes",
    label: "Programmes",
    order: "sort",
    columns: ["title", "category", "artist", "duration"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: ["katha", "bhajan", "dayro", "sangeet", "videos", "other"] },
      { name: "artist", label: "Artist / By", type: "text" },
      { name: "duration", label: "Duration", type: "text", hint: "e.g. 1:24:00" },
      { name: "tag", label: "Tag label", type: "text" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "video_url", label: "Video URL", type: "text" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  news: {
    table: "gyaan_news",
    label: "News & Blogs",
    order: "sort",
    columns: ["title", "language", "category", "is_ticker"],
    fields: [
      { name: "title", label: "Title / Headline", type: "text", required: true },
      { name: "language", label: "Language", type: "text", hint: "Type in ANY language — e.g. Hindi, Gujarati, English, Tamil, मराठी…" },
      { name: "category", label: "Category", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "body", label: "Full body", type: "textarea" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "is_ticker", label: "Show in news ticker", type: "bool" },
      { name: "published_at", label: "Published date", type: "date" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  events: {
    table: "gyaan_events",
    label: "Event Submissions",
    order: "created_at",
    ascending: false,
    columns: ["title", "organizer", "event_date", "status"],
    fields: [
      { name: "title", label: "Event title", type: "text", required: true },
      { name: "event_type", label: "Type", type: "text", hint: "e.g. Ram Katha, Bhajan Sandhya" },
      { name: "organizer", label: "Organizer", type: "text" },
      { name: "event_date", label: "Event date", type: "date" },
      { name: "place", label: "Place / Venue", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "contact_phone", label: "Contact phone", type: "text" },
      { name: "contact_email", label: "Contact email", type: "text" },
      { name: "image_url", label: "Poster / image URL", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"], hint: "Set to 'approved' to publish on the public Events page" },
      { name: "submitter_email", label: "Submitted by", type: "text" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  thought: {
    table: "gyaan_thought",
    label: "Thought of the Day",
    order: "created_at",
    columns: ["quote", "author", "active"],
    fields: [
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "author", label: "Author", type: "text" },
      { name: "active", label: "Active (shown on site)", type: "bool", hint: "Only one should be active" },
    ],
  },
  pilgrimage: {
    table: "gyaan_pilgrimage",
    label: "Pilgrimage",
    order: "sort",
    columns: ["name", "category", "place"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: ["shakti", "jyotirling", "mandir"] },
      { name: "place", label: "Place", type: "text" },
      { name: "significance", label: "Significance", type: "textarea" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  settings: {
    table: "gyaan_settings",
    label: "Site Settings",
    order: "key",
    pk: "key",
    columns: ["key", "value"],
    fields: [
      { name: "key", label: "Key", type: "text", required: true, pkField: true },
      { name: "value", label: "Value", type: "textarea" },
    ],
  },
};

export const ENTITY_KEYS = Object.keys(ENTITIES);
