const THUMBS = ["tg1", "tg2", "tg3", "tg4", "tg5", "tg6"];
const LISTING_CATS = ["temple", "artist", "kathakaar", "trust_ngo", "saint", "rishi", "personality", "other"];

export const ENTITIES = {
  banner: {
    table: "gyaan_banner",
    label: "Home Banner",
    order: "sort",
    columns: ["title", "eyebrow", "cta_label", "active"],
    fields: [
      { name: "title", label: "Banner heading", type: "text", required: true },
      { name: "eyebrow", label: "Small label (top)", type: "text", hint: "e.g. 🕉 Now Streaming" },
      { name: "subtitle", label: "Sub text", type: "textarea" },
      { name: "image_url", label: "Background image URL", type: "text", hint: "Optional — leave blank for the default gradient" },
      { name: "cta_label", label: "Button text", type: "text", hint: "e.g. Watch Live Now" },
      { name: "cta_link", label: "Button link", type: "text", hint: "e.g. /live or https://…" },
      { name: "active", label: "Show on home", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  listings: {
    table: "gyaan_listings",
    label: "Directory Listings",
    order: "created_at",
    ascending: false,
    columns: ["name", "category", "city", "status", "featured"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: LISTING_CATS, hint: "temple / artist / kathakaar / trust_ngo / saint / rishi / personality" },
      { name: "slug", label: "URL slug (mini-site)", type: "text", hint: "e.g. morari-bapu → /listing/morari-bapu" },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "about", label: "About", type: "textarea" },
      { name: "image_url", label: "Photo / Logo URL", type: "text" },
      { name: "cover_url", label: "Cover image URL", type: "text" },
      { name: "youtube_url", label: "Main YouTube link", type: "text" },
      { name: "videos", label: "More YouTube links", type: "textarea", hint: "One link per line" },
      { name: "place", label: "Place / Ashram", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "languages", label: "Languages", type: "text" },
      { name: "established", label: "Established", type: "text" },
      { name: "contact_phone", label: "Contact phone", type: "text" },
      { name: "contact_email", label: "Contact email", type: "text" },
      { name: "website", label: "Website", type: "text" },
      { name: "facebook", label: "Facebook URL", type: "text" },
      { name: "instagram", label: "Instagram URL", type: "text" },
      { name: "youtube_channel", label: "YouTube channel URL", type: "text" },
      { name: "seo_title", label: "SEO title", type: "text" },
      { name: "seo_description", label: "SEO description", type: "textarea" },
      { name: "featured", label: "Featured", type: "bool" },
      { name: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"], hint: "Set 'approved' to publish the mini-site" },
      { name: "submitter_email", label: "Submitted by", type: "text" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  kathakaar: {
    table: "gyaan_kathakaar",
    label: "Kathakaar",
    order: "sort",
    columns: ["name", "role", "place", "featured"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "initials", label: "Initials (avatar)", type: "text", hint: "e.g. MB" },
      { name: "role", label: "Role", type: "text", hint: "e.g. Ram Katha" },
      { name: "languages", label: "Languages", type: "text" },
      { name: "ashram", label: "Ashram", type: "text" },
      { name: "place", label: "Place", type: "text" },
      { name: "image_url", label: "Image URL", type: "text" },
      { name: "videos_url", label: "Videos URL", type: "text" },
      { name: "contact_phone", label: "Contact phone", type: "text" },
      { name: "contact_email", label: "Contact email", type: "text" },
      { name: "featured", label: "Featured on home", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  live: {
    table: "gyaan_live",
    label: "Live",
    order: "sort",
    columns: ["title", "kind", "place", "is_live"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "kind", label: "Type", type: "select", options: ["darshan", "katha"] },
      { name: "place", label: "Place / By", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "stream_url", label: "Stream URL", type: "text" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "viewers", label: "Viewers label", type: "text", hint: "e.g. 12.4k" },
      { name: "is_live", label: "Live now", type: "bool" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  programmes: {
    table: "gyaan_programmes",
    label: "Programmes",
    order: "sort",
    columns: ["title", "category", "artist", "duration"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: ["katha", "bhajan", "dayro", "sangeet", "videos", "other"] },
      { name: "artist", label: "Artist / By", type: "text" },
      { name: "duration", label: "Duration", type: "text", hint: "e.g. 1:24:00" },
      { name: "tag", label: "Tag label", type: "text" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "video_url", label: "Video URL", type: "text" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  news: {
    table: "gyaan_news",
    label: "News & Blogs",
    order: "sort",
    columns: ["title", "language", "category", "is_ticker"],
    fields: [
      { name: "title", label: "Title / Headline", type: "text", required: true },
      { name: "language", label: "Language", type: "text", hint: "Type in ANY language — e.g. Hindi, Gujarati, English, Tamil, मराठी…" },
      { name: "category", label: "Category", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "body", label: "Full body", type: "textarea" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "is_ticker", label: "Show in news ticker", type: "bool" },
      { name: "published_at", label: "Published date", type: "date" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  blogs: {
    table: "gyaan_blogs",
    label: "Blogs",
    order: "created_at",
    ascending: false,
    columns: ["title", "category", "language", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "URL slug", type: "text", hint: "e.g. temple-history → /blog/temple-history" },
      { name: "category", label: "Category", type: "text" },
      { name: "language", label: "Language", type: "text", hint: "Any language — Hindi, English, Gujarati…" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "body", label: "Full article", type: "textarea" },
      { name: "image_url", label: "Cover image URL", type: "text" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "youtube_url", label: "YouTube link (optional)", type: "text" },
      { name: "author", label: "Author", type: "text" },
      { name: "tags", label: "Tags", type: "text", hint: "comma separated" },
      { name: "seo_title", label: "SEO title", type: "text" },
      { name: "seo_description", label: "SEO description", type: "textarea" },
      { name: "published", label: "Published", type: "bool" },
      { name: "published_at", label: "Published date", type: "date" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  subscriptions: {
    table: "gyaan_subscriptions",
    label: "App Subscriptions",
    order: "created_at",
    ascending: false,
    columns: ["name", "phone", "plan", "amount", "status"],
    fields: [
      { name: "name", label: "Name", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "plan", label: "Plan", type: "select", options: ["annual_365", "gift_1_day"] },
      { name: "gift_for", label: "Gift for", type: "text" },
      { name: "amount", label: "Amount (₹)", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["new", "contacted", "paid", "active", "cancelled"] },
      { name: "note", label: "Note", type: "textarea" },
    ],
  },
  events: {
    table: "gyaan_events",
    label: "Event Submissions",
    order: "created_at",
    ascending: false,
    columns: ["title", "organizer", "event_date", "status"],
    fields: [
      { name: "title", label: "Event title", type: "text", required: true },
      { name: "event_type", label: "Type", type: "text", hint: "e.g. Ram Katha, Bhajan Sandhya" },
      { name: "organizer", label: "Organizer", type: "text" },
      { name: "event_date", label: "Event date", type: "date" },
      { name: "place", label: "Place / Venue", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "contact_phone", label: "Contact phone", type: "text" },
      { name: "contact_email", label: "Contact email", type: "text" },
      { name: "image_url", label: "Poster / image URL", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"], hint: "Set to 'approved' to publish on the public Events page" },
      { name: "submitter_email", label: "Submitted by", type: "text" },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  thought: {
    table: "gyaan_thought",
    label: "Thought of the Day",
    order: "created_at",
    columns: ["quote", "author", "active"],
    fields: [
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "author", label: "Author", type: "text" },
      { name: "active", label: "Active (shown on site)", type: "bool", hint: "Only one should be active" },
    ],
  },
  pilgrimage: {
    table: "gyaan_pilgrimage",
    label: "Pilgrimage",
    order: "sort",
    columns: ["name", "category", "place"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: ["shakti", "jyotirling", "mandir"] },
      { name: "place", label: "Place", type: "text" },
      { name: "significance", label: "Significance", type: "textarea" },
      { name: "thumb", label: "Thumbnail colour", type: "select", options: THUMBS },
      { name: "sort", label: "Sort order", type: "number" },
    ],
  },
  settings: {
    table: "gyaan_settings",
    label: "Site Settings",
    order: "key",
    pk: "key",
    columns: ["key", "value"],
    fields: [
      { name: "key", label: "Key", type: "text", required: true, pkField: true },
      { name: "value", label: "Value", type: "textarea" },
    ],
  },
};

export const ENTITY_KEYS = Object.keys(ENTITIES);
